export default `Andamiaje es una iniciativa curatorial que busca apoyar a artistas emergentes a través de un proyecto dirigido a un grupo exclusivo de miembros (20 coleccionistas) a los que se les ofrece formar parte de una nueva manera de coleccionar arte joven, al tiempo de hacerse de un grupo de obras seleccionadas por Patricia Martín. La propuesta curatorial pondrá en diálogo el trabajo de artistas con trayectorias diversas; la de aquellos que inician o que cuentan con poca visibilidad, con artistas que tienen una carrera ya consolidada, lo cual a su vez promoverá una suerte de mentoría para los artistas más nóveles estrechando y enriqueciendo la relación entre estos grupos de autores. El proyecto está diseñado para propiciar la inclusión y participación de otros actores del mundo del arte: galeristas, curadores y coleccionistas. En particular, la forma en que esta iniciativa busca involucrar a los galeristas, es a partir de una postura activa y no como competencia, ya que los resultados beneficiaran a todas las partes de forma recíproca.

Andamiaje surge del deseo de acompañar y proveer a un grupo de artistas con los elementos necesarios para resolver sus necesidades primarias y poder seguir produciendo, permitiendo que se enfoquen en la creación de su obra. Andamiaje se construye también a partir del interés latente por parte de personas por construir una buena colección y recibir una asesoría personalizada en dicho proceso.

Frente a la inmensa oferta del mundo del arte contemporáneo, surgen preguntas como: “¿Por dónde comenzar? ¿Cómo se arma una buena colección? ¿Qué futuro tendrá este artista? ¿Con que autoridad cuento para saber si esto es relevante? ¿Con qué criterios debe uno adquirir? Me gusta, pero no sé (...)”. Todas las anteriores son preguntas válidas, y aunque es imposible contar con respuestas universales o certezas irrevocables, un curador tiene la capacidad de catalizar y crear un puente, entre aquellos interesados y el complejo y particular mundo del arte. Andamiaje permite que sus miembros accedan a un universo de por sí vasto a través de un marco acotado y seguro, sustentado en la investigación y trayectoria de la curadora, quien introducirá, adaptará, y acompañará a este grupo de coleccionistas durante todo el proceso.

A partir de un modelo de inversión novedoso invitamos a que los participantes adquieran obras de 17 artistas, favoreciendo un diálogo estético, curatorial y formativo que va más allá de una simple transacción de compra-venta. La invitación se limita a un grupo cerrado de 20 coleccionistas, con quienes se comparten tres catálogos de obra al año, de manera tal que los miembros que conforman Andamiaje, quienes podrán escoger sus piezas a partir de una mecánica definida al inicio, recibiendo a lo largo del año el monto total de su inversión en obras de arte. Para fines propios del proyecto se ha creado una aplicación digital que sirve como plataforma, así como punto de encuentro e intercambio entre los miembros y las propuestas del proyecto.

La intención es crear un círculo virtuoso en el que todos ganan, abriendo la posibilidad a sus integrantes de formar parte de la futura escritura de la historia del arte contemporáneo en México.

Version: 1.1.1
`;
